/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353535",
        "primary-fixed-dim": "#ffb4a8",
        "inverse-on-surface": "#303030",
        "on-secondary-fixed-variant": "#454747",
        "error": "#ffb4ab",
        "surface-bright": "#393939",
        "surface-dim": "#131313",
        "secondary-container": "#454747",
        "on-primary": "#690100",
        "surface": "#131313",
        "background": "#131313",
        "secondary": "#c6c6c7",
        "inverse-primary": "#c00100",
        "on-secondary-container": "#b4b5b5",
        "on-error-container": "#ffdad6",
        "outline": "#b18780",
        "primary": "#ffb4a8",
        "tertiary-fixed-dim": "#acc7ff",
        "inverse-surface": "#e2e2e2",
        "primary-container": "#ff5540",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#d7e2ff",
        "secondary-fixed": "#e2e2e2",
        "on-surface-variant": "#ebbbb4",
        "on-tertiary-fixed-variant": "#004491",
        "on-primary-fixed-variant": "#930100",
        "on-error": "#690005",
        "on-secondary": "#2f3131",
        "on-tertiary": "#002f67",
        "on-tertiary-fixed": "#001a40",
        "on-primary-fixed": "#410000",
        "surface-container": "#1f1f1f",
        "on-background": "#e2e2e2",
        "on-primary-container": "#5c0000",
        "on-secondary-fixed": "#1a1c1c",
        "on-surface": "#e2e2e2",
        "primary-fixed": "#ffdad4",
        "surface-container-low": "#1b1b1b",
        "tertiary": "#acc7ff",
        "error-container": "#93000a",
        "outline-variant": "#603e39",
        "surface-tint": "#ffb4a8",
        "tertiary-container": "#488fff",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-container": "#00285b",
        "surface-container-highest": "#353535"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        md: "16px",
        xl: "48px",
        unit: "4px",
        gutter: "24px",
        lg: "24px",
        "container-max": "1280px",
        sm: "8px",
        xxl: "80px"
      },
      fontFamily: {
        h1: ["Space Grotesk"],
        "body-md": ["Space Grotesk"],
        "body-lg": ["Space Grotesk"],
        "display-xl": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        h2: ["Space Grotesk"],
        "label-caps": ["Space Grotesk"]
      },
      fontSize: {
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "5xl": ["3rem", { lineHeight: "1.2" }]
      }
    },
  },
  plugins: [],
}
